### ISSUE TITLE
missing MODIS datasets

### ISSUE THREAD

**Issue by alexisrc1** [gabrieltseng/pycrop-yield-prediction#1]
![image](https://user-images.githubusercontent.com/22400683/69191128-2ec9eb80-0b22-11ea-8ecb-6ad72ca57f8e.png)

hello,

i tried to install the virtual environment but the installation failed (see above)
i'd much appreciate if you could help :)

Alexis

**Comment by gabrieltseng** [comment]
Hi!
Sorry about that - could you try the environment file in #2 ?

**Comment by alexisrc1** [comment]
Thank you for your answer, it does work.

Obviously as it is never easy, I am running into another problem which
might be linked directly to the fact that modis datasets do not exist
anymore (here
<https://github.com/gabrieltseng/pycrop-yield-prediction/blob/master/data/README.md#MODIS>)
therefore I have the following error
[image: image.png]

Please dont feel obligated to spend time on it, I just wanted to try out
your model so no big deal :)


Best

Alexis

Le ven. 22 nov. 2019 à 06:01, Gabriel Tseng <notifications@github.com> a
écrit :

**Comment by gabrieltseng** [comment]
Nice!

Re: the MODIS datasets, could you reattach the image? It isn't showing up for me
