### ISSUE TITLE
Fusion tables are now deprecated

### ISSUE THREAD

**Issue by kushagra-2503** [gabrieltseng/pycrop-yield-prediction#3]
Can you suggest me an alternate, now that the fusion tables are not avaiable, and also the necessary changes ?

**Comment by gabrieltseng** [comment]
Hi! It looks like counties boundaries are available as an earth engine dataset:

https://developers.google.com/earth-engine/datasets/catalog/TIGER_2018_Counties

It's probably not a drop in replacement - I suspect the lines [here](https://github.com/gabrieltseng/pycrop-yield-prediction/blob/master/cyp/data/exporting.py#L153) will need to be changed.

I've made a note for myself to take a look, but it might take me a while to get to it

**Comment by kushagra-2503** [comment]
I tried using this dataset already, but my google drive folder is empty, after succesful completion. Any suggestions?

**Comment by gabrieltseng** [comment]
Hmm.. the files sometime take a while to show up in the google drive. How long ago did you run it?

Could you share the code you used to run it with the new dataset?

**Comment by kushagra-2503** [comment]
The code is almost the same as your code with a few tweaks. I am attaching the folder that has my code.
[modis_crop_yield.zip](https://github.com/gabrieltseng/pycrop-yield-prediction/files/4373170/modis_crop_yield.zip)

**Comment by kushagra-2503** [comment]
Did you find time to look at the code?

**Comment by gabrieltseng** [comment]
@kushagra-2503 , let me know if the code in the PR works for you.

I ran it and was able to export files - if it works for you, I'll merge it

**Comment by kushagra-2503** [comment]
The code works fine, thanks for your help.

**Comment by rongtongxueya** [comment]
sorry,i meet a question, I have run your code, but I don't know why I don't see the exported tif image? Is this a success?
![12](https://github.com/gabrieltseng/pycrop-yield-prediction/assets/97833507/d6e366ad-da26-41d1-a66c-bd822d8c6c31)

**Comment by gabrieltseng** [comment]
@rongtongxueya The tif files should be exported to your google drive - are you having trouble finding them there? 

They make take some time to export - you should be able to track the exports at the following URL: https://code.earthengine.google.com/tasks
