### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by husanpy** [gabrieltseng/pycrop-yield-prediction#8]
I tried to setup as in README, but got error: 

![image](https://user-images.githubusercontent.com/17599313/98660992-c219b380-2367-11eb-8c75-daca8e42c932.png)

**Comment by gabrieltseng** [comment]
Running the same command works for me - what version of conda are you running?

**Comment by husanpy** [comment]
I am so sorry. I tried to run it from PC at my work station and didn't look at its parameters. Then I checked it, and it was 32-bit so it's kinda impossible to deal with PyTorch on 32-bit system. My badness.
